services:
  controller:
    build:
      context: .
      dockerfile: deploy_app/Dockerfile.controller
        #image: nielsantosa/fastchat_controller
    restart: always
    ports:
      - 21001:21001
  backend_nat:
    build:
      context: .
      dockerfile: deploy_app/Dockerfile.backend_nat
        #image: nielsantosa/fastchat_backend_nat
    restart: always
    ports:
      - 21010:21010
    environment:
      - CONTROLLER_ADDRESS=http://controller:21001
