FROM python:3.11.3-bullseye

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
COPY requirements.txt .
RUN pip3 install --no-cache-dir wheel==0.38.4 pip==22.3.1 && \
    pip3 install --no-cache-dir -r /requirements.txt

# Run the application:
ENV PYTHONPATH=/
COPY . /
CMD ["python3", "fastchat/serve/controller.py"]
